name: My Jekyll Website
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3
  parse_block_html: true

collections:
    series:
        output: true

defaults:
    scope:
        path: ""
        type: "series"
    values:
        layout: "series"
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"
    scope:
        path: ""
    values:
        layout: "default"

